[package]
name = "solana-transaction-builder"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
anchor-client = "^0.27.0"
base64 = "0.13.0"
bincode = "1.3.3"
borsh = ">=0.9, <0.11" # anchor dependent
log = "0.4.21"
once_cell = "1.19.0"
solana-sdk = "1.17.22"
thiserror = "1.0.58"
