name: Cargo lint
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev pkg-config

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 20

      - name: 🦿 Install Rust tookchain
        uses: dtolnay/rust-toolchain@5cdfcfbd9e32fbc2e562bfc289a94537ca9dba61 # 1.75.0

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧭 Run cargo lint
        run: cargo fmt -- --check && cargo clippy -- -D warnings

      - name: 🧨 Run cargo tests
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: test
          args: --all-features
